version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672 

  exercicio-dxc:
    image: emersondiaspd/exercicio-dxc:0.0.1-SNAPSHOT
    build:
      dockerfile: Dockerfile
    ports:
      - 8181:8181
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      
      
