
rabbitmq:
  image: rabbitmq:3.11-management
  ports:
    - "5672:5672" # AMQP protocol port
    - "15672:15672" # HTTP management UI

exercicio-dxc:
  image: emersondiaspd/exercicio-dxc:0.0.1-SNAPSHOT
  links:
    - rabbitmq
  ports:
    #  local : container expose
    - "8181:8181"
  environment:
    RABBIT_HOST: rabbitmq
