version: '3.8'

services:
      
  rabbit-mq:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    image: rabbitmq:3.11-management
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
    ports:
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'
    networks:
      - dxc
            
  exercicio-dxc:
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3
    image: emersondiaspd/exercicio-dxc:0.0.1-SNAPSHOT
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 8181:8181
    depends_on:
      - rabbit-mq
    networks:
      - dxc
      
networks:
  dxc:
    external: true

        
