version: '3.8'

services:
    rabbitmq:
      image: rabbitmq:11-management
      container_name: rabbitmq  
      restart: always
      ports:
        - "15672:15672"
        - "5672:5672"

    exercicio-dxc:                        
      image: exercicio-dxc              
      container_name: exercicio-dxc
      build:
        context: .                          
        dockerfile: Dockerfile             
      ports:
        - "8181:8181"                      
      restart: always
      environment:
        - SPRING_RABBITMQ_HOST=rabbitmq  
      depends_on:                           
        - rabbitmq           
        
