name: Continous Integration with GitHub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
                                 
      - name: Build Exercicio DXC Jar
        working-directory: ./
        run: mvn clean package -DskipTests
      
      - name: Docker Compose Build
        run: docker-compose build
        
      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/exercicio-dxc:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/exercicio-dxc:0.0.1-SNAPSHOT
          docker push ${{ secrets.DOCKER_USERNAME }}/exercicio-dxc:0.0.1-SNAPSHOT
          
